[package]
name = "storage-engine"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
bincode.workspace = true
anyhow.workspace = true
thiserror.workspace = true

