[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
storage = { path = "../storage" }
parser = { path = "../parser" }
anyhow.workspace = true
thiserror.workspace = true
serde_json = "1.0"

